### ISSUE TITLE
Conflict and exception with traw/powermailcaptcha and powermail_cleaner

### ISSUE THREAD

**Issue by sypets** [in2code-de/powermail_cleaner#1]
I think there is a conflict between powermailcaptcha and powermail_cleaner because they both XCLASS FormController.

Short term solution could be to add a "conflicts" in composer.json for this.

I had other extensions too where more than one extension tries to XCLASS. It is possible to solve this, but it is messy.

Perhaps there is another way to provide the behaviour without having to XCLASS? That would be the preferable solution in my opinion. FormController already sends an event. Ideal would also be if extensions which provide a captcha solution would not have to XCLASS.

## Reproduce

1. Install powermail, powermail_cleaner und powermailcaptcha (`composer require traw/powermailcaptcha ...`)
2. Create a minimal working form
3. Fill out form and send

```
An Exception is thrown:

(1/1) Error
Call to undefined method TRAW\Powermailcaptcha\Controller\FormController::getContentObject()

in /var/www/t3intro12/vendor/in2code/powermail_cleaner/Classes/EventListener/FormControllerCreateActionBeforeRenderViewEventListener.php line 25
        /** @var Mail $mail */
        $mail = $event->getMail();
        $hash = $event->getHash();

        $mail->setPlugin($controller->getContentObject()->data['uid']);
        $mail->setDeletionTimestamp($this->calculateDeletionTimeStamp($controller));

        $event->setMail($mail);
```

## VErsions

To verify issue, I used a "clean" installation with minimal configuration:

* TYPO3 12.4.8
* PHP 8.2
* powermail 12.4.2
* powermail_cleaner 5.2.0
* powermailcaptcha 2.1.1

With following static includes:

![image](https://github.com/user-attachments/assets/c80023af-df04-4493-a0a8-e5de29fe8d15)

**Comment by sypets** [comment]
[in2code/powermailrecaptcha](https://extensions.typo3.org/extension/powermailrecaptcha) does not have the same problem. It does not XCLASS anything.

In that case, you could argue, it is the problem of traw/powermailcaptcha and not powermail_cleaner or powermail.

(Probably the extension author could use the event, which already exists. I will check).

However, I still think the multiple XCLASSes are probably not the best solution (especially since both extensions are from the same vendor). powermail_cleaner comes with 4.

I will update the issue. Please feel free to close.

**Comment by sbusemann** [comment]
https://projekte.in2code.de/issues/62855?
